In [1]:
#Matrix Market file and converts it to an adjacency matrix
#file_path: Path to the Matrix Market file
#return: Adjacency matrix as a NumPy array

In [2]:
!pip install numpy scipy

In [3]:
import numpy as np
from scipy.io import mmread

In [4]:
def read_matrix_market_file(file_path):

    # Read the Matrix Market file
    matrix = mmread(file_path)

    # Convert the sparse matrix to a dense matrix
    adjacency_matrix = matrix.toarray()

    return adjacency_matrix

def save_to_text_file(matrix, file_path):
    np.savetxt(file_path, matrix, fmt='%d')

if __name__ == "__main__":
    file_path = '/content/C4000-5.mtx'  # Replace with your actual file path
    adjacency_matrix = read_matrix_market_file(file_path)

    # Print the adjacency matrix
    print(adjacency_matrix)


[[0. 1. 1. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [5]:
# Save the adjacency matrix to a text file
save_to_text_file(adjacency_matrix, '/content/adjacency_matrix.txt')
print(adjacency_matrix)

[[0. 1. 1. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
